### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by spekulazarus** [strapi-community/strapi-tool-dockerize#112]
## ⛔️  Error log

Command failed with exit code 1: yarn add mysql
[31m[1mUsage Error[22m[39m: The nearest package directory (/Users/fabianmargane/my-project) doesn't seem to be part of the project declared in /Users/fabianmargane.

- If /Users/fabianmargane isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/fabianmargane is intended to be a project, it might be that you forgot to list my-project in its workspace configuration.
- Finally, if /Users/fabianmargane is fine and you intend my-project to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

[1m$ [22myarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add mysql
[31m[1mUsage Error[22m[39m: The nearest package directory (/Users/fabianmargane/my-project) doesn't seem to be part of the project declared in /Users/fabianmargane.

- If /Users/fabianmargane isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/fabianmargane is intended to be a project, it might be that you forgot to list my-project in its workspace configuration.
- Finally, if /Users/fabianmargane is fine and you intend my-project to be treated as a completely separate project (not even a workspace), create an empty yarn.lock file in it.

[1m$ [22myarn add [--json] [-F,--fixed] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
    at makeError (/Users/fabianmargane/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/fabianmargane/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/Users/fabianmargane/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/fabianmargane/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v20.12.2
- 💻  OS: darwin arm64

**Comment by Eventyret** [comment]
Closing as part of v2.5 rewrite. This version is a complete rewrite with improved Docker support for Strapi v4/v5. If this issue persists after v2.5 is released, please reopen or file a new issue.
