### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by ndthanh143** [strapi-community/strapi-tool-dockerize#113]
## ⛔️  Error log

Command failed with exit code 1: yarn add pg
error flower-server@0.1.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "21.7.1"
error Found incompatible module.
yarn add v1.22.21
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add pg
error flower-server@0.1.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "21.7.1"
error Found incompatible module.
yarn add v1.22.21
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (/Users/macos/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/macos/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/Users/macos/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/macos/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v21.7.1
- 💻  OS: darwin x64

**Comment by Eventyret** [comment]
Your using node 21 not 20 downgrade node js
