### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by ranji94** [strapi-community/strapi-tool-dockerize#115]
## ⛔️  Error log

Command failed with exit code 1: npm install pg
npm error code ERR_INVALID_ARG_TYPE
npm error The "path" argument must be of type string or an instance of Buffer or URL. Received null
npm error A complete log of this run can be found in: C:\Users\jedrz\AppData\Local\npm-cache\_logs\2024-05-23T19_18_16_604Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install pg
npm error code ERR_INVALID_ARG_TYPE
npm error The "path" argument must be of type string or an instance of Buffer or URL. Received null
npm error A complete log of this run can be found in: C:\Users\jedrz\AppData\Local\npm-cache\_logs\2024-05-23T19_18_16_604Z-debug-0.log
    at makeError (C:\Users\jedrz\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\jedrz\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (C:\Users\jedrz\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\@strapi-community\dockerize\core\dependencies.js:21:3)
    at async C:\Users\jedrz\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\@strapi-community\dockerize\index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v18.19.0
- 💻  OS: win32 x64

**Comment by Eventyret** [comment]
No info provided can't replicate
