### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by olgierdfrontrunners** [strapi-community/strapi-tool-dockerize#121]
## ⛔️  Error log

Command failed with exit code 1: yarn add mysql
error @strapi/plugin-graphql@4.25.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "16.15.1"
error Found incompatible module.
yarn add v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add mysql
error @strapi/plugin-graphql@4.25.1: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "16.15.1"
error Found incompatible module.
yarn add v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (C:\Users\OlgierdFrontrunnersM\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\OlgierdFrontrunnersM\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDependecies (C:\Users\OlgierdFrontrunnersM\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\@strapi-community\dockerize\core\dependencies.js:21:3)
    at async C:\Users\OlgierdFrontrunnersM\AppData\Local\npm-cache\_npx\a642ee8303c0fc2f\node_modules\@strapi-community\dockerize\index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.15.1
- 💻  OS: win32 x64

**Comment by Eventyret** [comment]
Seems you need to update your node to min 18 as you are using 16

**Comment by Eventyret** [comment]
Closing as part of v2.5 rewrite. This version is a complete rewrite with improved Docker support for Strapi v4/v5. If this issue persists after v2.5 is released, please reopen or file a new issue.
