### ISSUE TITLE
npm install mysql failed

### ISSUE THREAD

**Issue by kobeliuke** [strapi-community/strapi-tool-dockerize#123]
## ⛔️  Error log

Command failed with exit code 1: npm install mysql
npm error code ERR_INVALID_ARG_TYPE
npm error The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm error A complete log of this run can be found in: /Users/will/.npm/_logs/2024-07-06T04_49_32_742Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install mysql
npm error code ERR_INVALID_ARG_TYPE
npm error The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm error A complete log of this run can be found in: /Users/will/.npm/_logs/2024-07-06T04_49_32_742Z-debug-0.log
    at makeError (/Users/will/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/will/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/Users/will/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/will/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v20.15.0
- 💻  OS: darwin arm64

**Comment by pct-tploeger** [comment]
I encountered the same issue today. Deleting the empty "yarn.lock" folder in my strapi project worked for me.

**Comment by Eventyret** [comment]
Closing as part of v2.5 rewrite. This version is a complete rewrite with improved Docker support for Strapi v4/v5. If this issue persists after v2.5 is released, please reopen or file a new issue.
