### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by MattHarr1s** [strapi-community/strapi-tool-dockerize#126]
## ⛔️  Error log

Command failed with exit code 1: yarn add mysql
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0082: │ lru-cache@npm:^10.2.0: No candidates found
➤ YN0000: └ Completed in 2s 201ms
➤ YN0000: · Failed with errors in 2s 215ms

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add mysql
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: │ MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
➤ YN0082: │ lru-cache@npm:^10.2.0: No candidates found
➤ YN0000: └ Completed in 2s 201ms
➤ YN0000: · Failed with errors in 2s 215ms
    at makeError (/home/matt/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/matt/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/home/matt/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/matt/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v20.9.0
- 💻  OS: linux x64

**Comment by Eventyret** [comment]
Closing as part of v2.5 rewrite. This version is a complete rewrite with improved Docker support for Strapi v4/v5. If this issue persists after v2.5 is released, please reopen or file a new issue.
