### ISSUE TITLE
Error: strapi database docker error

### ISSUE THREAD

**Issue by cey0** [strapi-community/strapi-tool-dockerize#129]
## ⛔️  Error log

Command failed with exit code 1: yarn add pg
warning @strapi/plugin-users-permissions > react-query > match-sorter@6.4.0: This was arguably a breaking change. Not in API, but more results can be returned. Upgrade to the next major when you are ready for that
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @strapi/strapi > yalc > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > copyfiles > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > yalc > npm-packlist > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @strapi/strapi > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/core > global-agent > boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @strapi/strapi > @strapi/core > global-agent > roarr > boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @strapi/strapi > @strapi/generators > node-plop > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/strapi > @strapi/generators > plop > node-plop > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/strapi > @strapi/generators > node-plop > globby > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > @strapi/email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
error @strapi/pack-up@5.0.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.9.0"
error Found incompatible module.
yarn add v1.22.22
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add pg
warning @strapi/plugin-users-permissions > react-query > match-sorter@6.4.0: This was arguably a breaking change. Not in API, but more results can be returned. Upgrade to the next major when you are ready for that
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/plugin-users-permissions > react-query > broadcast-channel > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning @strapi/strapi > yalc > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > copyfiles > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > yalc > npm-packlist > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @strapi/strapi > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/core > global-agent > boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @strapi/strapi > @strapi/core > global-agent > roarr > boolean@3.2.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @strapi/strapi > @strapi/generators > node-plop > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/strapi > @strapi/generators > plop > node-plop > del > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning @strapi/strapi > @strapi/generators > node-plop > globby > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning @strapi/strapi > @strapi/email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
error @strapi/pack-up@5.0.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0 <=20.x.x". Got "22.9.0"
error Found incompatible module.
yarn add v1.22.22
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (/home/cey0/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/cey0/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async installDependecies (/home/cey0/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/cey0/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v22.9.0
- 💻  OS: linux x64

**Comment by Eventyret** [comment]
Closing as part of v2.5 rewrite. This version is a complete rewrite with improved Docker support for Strapi v4/v5. If this issue persists after v2.5 is released, please reopen or file a new issue.
