### ISSUE TITLE
Error: Command failed with exit code 243: npm install pgnpm ERR! code EACCESnpm ERR! syscall mkdirnpm ERR! path /home/gost/node_modules/pgnpm ERR! errno -13npm ERR! Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'npm ERR!  [Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'] {npm ERR!   errno: -13,npm ERR!   code: 'EACCES',npm ERR!   syscall: 'mkdir',npm ERR!   path: '/home/gost/node_modules/pg'npm ERR! }npm ERR! npm ERR! The operation was rejected by your operating system.npm ERR! It is likely you do not have the permissions to access this file as the current usernpm ERR! npm ERR! If you believe this might be a permissions issue, please double-check thenpm ERR! permissions of the file and its containing directories, or try runningnpm ERR! the command again as root/Administrator.npm ERR! A complete log of this run can be found in:npm ERR!     /home/gost/.npm/_logs/2022-11-04T22_54_15_742Z-debug-0.log

### ISSUE THREAD

**Issue by gstrainovic** [strapi-community/strapi-tool-dockerize#41]
## ⛔️  Error log

Command failed with exit code 243: npm install pg
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/gost/node_modules/pg
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'
npm ERR!  [Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/gost/node_modules/pg'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gost/.npm/_logs/2022-11-04T22_54_15_742Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 243: npm install pg
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /home/gost/node_modules/pg
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'
npm ERR!  [Error: EACCES: permission denied, mkdir '/home/gost/node_modules/pg'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/gost/node_modules/pg'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gost/.npm/_logs/2022-11-04T22_54_15_742Z-debug-0.log
    at makeError (/home/gost/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/gost/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDependecies (/home/gost/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/gost/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:50:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.14.0
- 💻  OS: linux x64

**Comment by gstrainovic** [comment]
After sudo rm /home/gost/node_modules/ -rf it works
