### ISSUE TITLE
`Could not find Custom Field: plugin::field-uuid.uuid`

### ISSUE THREAD

**Issue by chaeyan** [strapi-community/strapi-tool-dockerize#46]
I got the UUID plugin on my strapi and when i tried this dockerize, i ran the server with docker compose up -d and then the server kept throwing this error
```
content-mgmt    | $ strapi develop
content-mgmt    | [2022-12-26 03:48:41.602] debug: ⛔️ Server wasn't able to start properly.
content-mgmt    | [2022-12-26 03:48:41.605] error: Could not find Custom Field: plugin::field-uuid.uuid
content-mgmt    | Error: Could not find Custom Field: plugin::field-uuid.uuid
content-mgmt    |     at Object.get (/opt/node_modules/@strapi/strapi/lib/core/registries/custom-fields.js:34:15)
content-mgmt    |     at convertCustomFieldType (/opt/node_modules/@strapi/strapi/lib/utils/convert-custom-field-type.js:15:67)
content-mgmt    |     at Strapi.register (/opt/node_modules/@strapi/strapi/lib/Strapi.js:398:5)
content-mgmt    |     at async Strapi.load (/opt/node_modules/@strapi/strapi/lib/Strapi.js:477:5)
content-mgmt    |     at async Strapi.start (/opt/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
content-mgmt    | error Command failed with exit code 1.
content-mgmt    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Eventyret** [comment]
Don't think this is the tool, but check that you are binding copying things over.

Have you done any modifications to the dockerfile or docker compose?

**Comment by Eventyret** [comment]
You also might want to check that it's not an old image your trying to run 😊

**Comment by Eventyret** [comment]
@chaeyan did you solve this or ?

**Comment by chaeyan** [comment]
I did, thanks
