### ISSUE TITLE
Error: Command failed with exit code 1: yarn add pgError: EISDIR: illegal operation on a directory, read    at Object.readSync (node:fs:723:3)    at tryReadSync (node:fs:433:20)    at Object.readFileSync (node:fs:479:19)    at onUnexpectedError (/Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100586:102)    at /Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100698:9yarn add v1.22.17

### ISSUE THREAD

**Issue by eubash** [strapi-community/strapi-tool-dockerize#52]
## ⛔️  Error log

Command failed with exit code 1: yarn add pg
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at onUnexpectedError (/Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100586:102)
    at /Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100698:9
yarn add v1.22.17

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add pg
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at onUnexpectedError (/Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100586:102)
    at /Users/evgeniya/.yarn/releases/yarn-1.22.17.cjs:100698:9
yarn add v1.22.17
    at makeError (/Users/evgeniya/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/evgeniya/.npm/_npx/a642ee8303c0fc2f/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async installDependecies (/Users/evgeniya/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/evgeniya/.npm/_npx/a642ee8303c0fc2f/node_modules/@strapi-community/dockerize/index.js:57:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v16.10.0
- 💻  OS: darwin arm64

**Comment by Eventyret** [comment]
Could you also check if `yarn.lock` is a file and not a folder @eubash

**Comment by Eventyret** [comment]
Closing this, if you still have an issue please re-open or create a new issue and give more context so this can be looked into
