### ISSUE TITLE
Error: Command failed with exit code 1: npm install pgnpm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!npm ERR! code EBADPLATFORMnpm ERR! notsup Unsupported platform for esbuild-android-64@0.15.18: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})npm ERR! notsup Valid OS:    androidnpm ERR! notsup Valid Arch:  x64npm ERR! notsup Actual OS:   darwinnpm ERR! notsup Actual Arch: x64npm ERR! A complete log of this run can be found in:npm ERR!     /Users/mehulkalathiya/.npm/_logs/2023-01-16T05_41_23_413Z-debug.log

### ISSUE THREAD

**Issue by mehulk13899** [strapi-community/strapi-tool-dockerize#53]
## ⛔️  Error log

Command failed with exit code 1: npm install pg
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-android-64@0.15.18: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    android
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mehulkalathiya/.npm/_logs/2023-01-16T05_41_23_413Z-debug.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install pg
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for esbuild-android-64@0.15.18: wanted {"os":"android","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    android
npm ERR! notsup Valid Arch:  x64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mehulkalathiya/.npm/_logs/2023-01-16T05_41_23_413Z-debug.log
    at makeError (/Users/mehulkalathiya/.npm/_npx/35794/lib/node_modules/@strapi-community/dockerize/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/mehulkalathiya/.npm/_npx/35794/lib/node_modules/@strapi-community/dockerize/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async installDependecies (/Users/mehulkalathiya/.npm/_npx/35794/lib/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /Users/mehulkalathiya/.npm/_npx/35794/lib/node_modules/@strapi-community/dockerize/index.js:57:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v14.19.0
- 💻  OS: darwin x64

**Comment by Eventyret** [comment]
So first it's trying to build for android . But you are on Mac.

I will need more info on what command you ran etc

**Comment by Eventyret** [comment]
No info given, please reopen the issue if you can provide some more context to the error @mehulk13899
