### ISSUE TITLE
Error: Command failed with exit code 1: yarn add pgERROR: [Errno 2] No such file or directory: 'add'

### ISSUE THREAD

**Issue by mrgobbo** [strapi-community/strapi-tool-dockerize#56]
## ⛔️  Error log

Command failed with exit code 1: yarn add pg
ERROR: [Errno 2] No such file or directory: 'add'

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add pg
ERROR: [Errno 2] No such file or directory: 'add'
    at makeError (/home/mario/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/mario/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/home/mario/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/mario/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:57:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v18.14.0
- 💻  OS: linux x64

**Comment by mrgobbo** [comment]
Sorry, it opened the issue automatically, seems to be my mistake setting the environment
