### ISSUE TITLE
Error: Command failed with exit code 1: yarn add pgerror strapi@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "19.6.0"error Found incompatible module.yarn add v1.22.19[1/5] Validating package.json...info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### ISSUE THREAD

**Issue by asavienko** [strapi-community/strapi-tool-dockerize#60]
## ⛔️  Error log

Command failed with exit code 1: yarn add pg
error strapi@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "19.6.0"
error Found incompatible module.
yarn add v1.22.19
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: yarn add pg
error strapi@0.1.0: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "19.6.0"
error Found incompatible module.
yarn add v1.22.19
[1/5] Validating package.json...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    at makeError (/home/asavienko/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/asavienko/.npm/_npx/c78dafd2dc881eeb/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (/home/asavienko/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/core/dependencies.js:21:3)
    at async /home/asavienko/.npm/_npx/c78dafd2dc881eeb/node_modules/@strapi-community/dockerize/index.js:57:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v19.6.0
- 💻  OS: linux x64

**Comment by Eventyret** [comment]
You will need to use node 16-18 and not 19 :)
