### ISSUE TITLE
Error: Command failed with ENOENT: npm install pgspawn npm ENOENT

### ISSUE THREAD

**Issue by vichnyi-myzuka** [strapi-community/strapi-tool-dockerize#61]
## ⛔️  Error log

Command failed with ENOENT: npm install pg
spawn npm ENOENT

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with ENOENT: npm install pg
spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v14.17.6
- 💻  OS: darwin x64

**Comment by Quentin-Sch** [comment]
what was the reason ?
