### ISSUE TITLE
TS container does not start and errors are about JS files.

### ISSUE THREAD

**Issue by askpatrickw** [strapi-community/strapi-tool-dockerize#74]
## 🤷‍♀️ What did you do

```bash
npx @strapi-community/dockerize
 Do you want to create a new Strapi Project … No / Yes
✔ Whats the name of the project? … dock
✔ Do you want to use TypeScript … No / Yes
✔ Do you want to assign a path for new project ? (leave blank for current directory ) … /Users/patrickwalters/code/exit83/strapi-test
(...)
 Do you want to create a docker-compose file? 🐳 … No / Yes
✔ What environment do you want to configure for? › Development
🐳  Dockerfile for DEVELOPMENT added

docker build ./
docker run <image_id>
```

## ⛔️ Error log

```bash
Starting the compilation for TypeScript files in /opt/app
Error: Middleware "strapi::session": App keys are required. Please set app.keys in config/server.js (ex: keys: ['myKeyA', 'myKeyB'])
    at instantiateMiddleware (/opt/node_modules/@strapi/strapi/lib/services/server/middleware.js:13:11)
    at resolveMiddlewares (/opt/node_modules/@strapi/strapi/lib/services/server/middleware.js:57:18)
    at registerApplicationMiddlewares (/opt/node_modules/@strapi/strapi/lib/services/server/register-middlewares.js:66:29)
    at async Object.initMiddlewares (/opt/node_modules/@strapi/strapi/lib/services/server/index.js:102:7)
    at async Strapi.bootstrap (/opt/node_modules/@strapi/strapi/lib/Strapi.js:477:5)
    at async Strapi.load (/opt/node_modules/@strapi/strapi/lib/Strapi.js:491:5)
    at async workerProcess (/opt/node_modules/@strapi/strapi/lib/commands/actions/develop/action.js:110:26)
```

## 🙇‍♀️ Expected behavior/code

I expected the container to start.

I definitely did not expect to see an error reference in a .JS file in a .TS project.

```bash
ls config
admin.ts       api.ts         database.ts    middlewares.ts server.ts
```

```
cat Dockerfile

FROM node:16-alpine
# Installing libvips-dev for sharp Compatability
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]
```

**Comment by Eventyret** [comment]
@SudeepPatel-0812 want to have a look?

**Comment by SudeepPatel-0812** [comment]
Hi @Eventyret yes sure I'll work on it. Thanks!

**Comment by Eventyret** [comment]
I can't replicate this @askpatrickw but the error suggests you have not created the `.env` file.

**Comment by Eventyret** [comment]
Replicated, will try test this a bit more.
