### ISSUE TITLE
Error: Please add a title

### ISSUE THREAD

**Issue by Lippones** [strapi-community/strapi-tool-dockerize#85]
## ⛔️  Error log

Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BTTIS\AppData\Local\npm-cache\_logs\2023-07-05T12_41_38_082Z-debug-0.log

### 🕵️‍♀️ Stack trace

```bash
Error: Command failed with exit code 1: npm install pg
npm ERR! code ERR_INVALID_ARG_TYPE
npm ERR! The "path" argument must be of type string or an instance of Buffer or URL. Received null

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BTTIS\AppData\Local\npm-cache\_logs\2023-07-05T12_41_38_082Z-debug-0.log
    at makeError (C:\Users\BTTIS\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\BTTIS\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependecies (C:\Users\BTTIS\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\core\dependencies.js:21:3)
    at async C:\Users\BTTIS\AppData\Local\npm-cache\_npx\c78dafd2dc881eeb\node_modules\@strapi-community\dockerize\index.js:63:4
```

## 🙇‍♀️  Expected behavior/code

A clear and concise description of what you expected to happen (or code).

## 👩‍💻 Environment

- 📦  Node version:  v18.16.0
- 💻  OS: win32 x64

**Comment by Eventyret** [comment]
Can you provide more information, like what command you ran etc.

**Comment by Eventyret** [comment]
No information provided closing
