### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by francocsanchez** [strapi-community/strapi-tool-dockerize#96]
I have this problem whit use MySQL

```
> bot@0.1.0 develop
> strapi develop

Building your admin UI with development configuration...
Admin UI built successfully
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Sequence._packetToError (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/francocsanchez/www/strapi/bot/node_modules/mysql/lib/Connection.js:116:18)
    at /Users/francocsanchez/www/strapi/bot/node_modules/knex/lib/dialects/mysql/index.js:66:18
    at new Promise (<anonymous>)
    at Client_MySQL.acquireRawConnection (/Users/francocsanchez/www/strapi/bot/node_modules/knex/lib/dialects/mysql/index.js:61:12)
    at create (/Users/francocsanchez/www/strapi/bot/node_modules/knex/lib/client.js:262:39) {
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
}
```

**Comment by Eventyret** [comment]
What is the contenet of your `docker-compose` file please
